In [1]:
#change directory
%cd "C:\Users\jwill\Documents\Lumen\One Hot"

C:\Users\jwill\Documents\Lumen\One Hot

In [2]:
# import libraries
import numpy as np
import pandas as pd

In [5]:
# import the data 
data = pd.read_csv('Nominal.csv')
data

     Color          Shape     Pets
0      Red         Square      Cat
1     Blue       Triangle      Dog
2    Green  Parallelogram    Snake
3   Violet      Trapezoid   Turtle
4      Red         Square      Dog
5   Yellow         Circle      Dog
6   Orange           Oval      Cat
7     Blue       Triangle  Hamster
8     Blue         Square      Dog
9    Green  Parallelogram      Cat
10   Green      Trapezoid      Dog
11  Yellow      Rectangle     Fish
12  Orange        Hexagon      Dog
13    Blue       Pentagon      Cat
14     Red         Circle      Cat
15     Red           Oval      Dog
16  Yellow        Octagon    Snake
17  Orange      Trapezoid   Turtle
18     Red         Square      Dog
19    Blue       Triangle      Dog
20   Green  Parallelogram      Cat
21  Yellow         Circle  Hamster
22  Orange        Hexagon      Dog
23  Orange           Oval      Cat
24   Green  Parallelogram      Dog
25    Blue       Pentagon     Fish
26  Yellow      Rectangle      Dog
27     Red         Square      Cat
28  Yellow      Rectangle      Dog
29  Orange        Hexagon      Cat
30   Green      Trapezoid  Hamster
31    Blue       Triangle      Dog

In [6]:
# Check the data
data['Pets'].value_counts()

Dog        14
Cat         9
Hamster     3
Fish        2
Turtle      2
Snake       2
Name: Pets, dtype: int64

In [7]:
# One-Hot Encoding
one_hot_encoded_data = pd.get_dummies(data, columns = ['Color', 'Shape','Pets'])
print(one_hot_encoded_data)

    Color_Blue  Color_Green  Color_Orange  Color_Red  Color_Violet  \
0            0            0             0          1             0
1            1            0             0          0             0
2            0            1             0          0             0
3            0            0             0          0             1
4            0            0             0          1             0
5            0            0             0          0             0
6            0            0             1          0             0
7            1            0             0          0             0
8            1            0             0          0             0
9            0            1             0          0             0
10           0            1             0          0             0
11           0            0             0          0             0
12           0            0             1          0             0
13           1            0             0          0             0
14           0            0             0          1             0
15           0            0             0          1             0
16           0            0             0          0             0
17           0            0             1          0             0
18           0            0             0          1             0
19           1            0             0          0             0
20           0            1             0          0             0
21           0            0             0          0             0
22           0            0             1          0             0
23           0            0             1          0             0
24           0            1             0          0             0
25           1            0             0          0             0
26           0            0             0          0             0
27           0            0             0          1             0
28           0            0             0          0             0
29           0            0             1          0             0
30           0            1             0          0             0
31           1            0             0          0             0

    Color_Yellow  Shape_Circle  Shape_Hexagon  Shape_Octagon  Shape_Oval  ...  \
0              0             0              0              0           0  ...
1              0             0              0              0           0  ...
2              0             0              0              0           0  ...
3              0             0              0              0           0  ...
4              0             0              0              0           0  ...
5              1             1              0              0           0  ...
6              0             0              0              0           1  ...
7              0             0              0              0           0  ...
8              0             0              0              0           0  ...
9              0             0              0              0           0  ...
10             0             0              0              0           0  ...
11             1             0              0              0           0  ...
12             0             0              1              0           0  ...
13             0             0              0              0           0  ...
14             0             1              0              0           0  ...
15             0             0              0              0           1  ...
16             1             0              0              1           0  ...
17             0             0              0              0           0  ...
18             0             0              0              0           0  ...
19             0             0              0              0           0  ...
20             0             0              0              0           0  ...
21             1             1              0              0           0  ...
22             0             0              1              0           0  ...
23             0             0              0              0           1  ...
24             0             0              0              0           0  ...
25             0             0              0              0           0  ...
26             1             0              0              0           0  ...
27             0             0              0              0           0  ...
28             1             0              0              0           0  ...
29             0             0              1              0           0  ...
30             0             0              0              0           0  ...
31             0             0              0              0           0  ...

    Shape_Rectangle  Shape_Square  Shape_Trapezoid  Shape_Triangle  Pets_Cat  \
0                 0             1                0               0         1
1                 0             0                0               1         0
2                 0             0                0               0         0
3                 0             0                1               0         0
4                 0             1                0               0         0
5                 0             0                0               0         0
6                 0             0                0               0         1
7                 0             0                0               1         0
8                 0             1                0               0         0
9                 0             0                0               0         1
10                0             0                1               0         0
11                1             0                0               0         0
12                0             0                0               0         0
13                0             0                0               0         1
14                0             0                0               0         1
15                0             0                0               0         0
16                0             0                0               0         0
17                0             0                1               0         0
18                0             1                0               0         0
19                0             0                0               1         0
20                0             0                0               0         1
21                0             0                0               0         0
22                0             0                0               0         0
23                0             0                0               0         1
24                0             0                0               0         0
25                0             0                0               0         0
26                1             0                0               0         0
27                0             1                0               0         1
28                1             0                0               0         0
29                0             0                0               0         1
30                0             0                1               0         0
31                0             0                0               1         0

    Pets_Dog  Pets_Fish  Pets_Hamster  Pets_Snake  Pets_Turtle
0          0          0             0           0            0
1          1          0             0           0            0
2          0          0             0           1            0
3          0          0             0           0            1
4          1          0             0           0            0
5          1          0             0           0            0
6          0          0             0           0            0
7          0          0             1           0            0
8          1          0             0           0            0
9          0          0             0           0            0
10         1          0             0           0            0
11         0          1             0           0            0
12         1          0             0           0            0
13         0          0             0           0            0
14         0          0             0           0            0
15         1          0             0           0            0
16         0          0             0           1            0
17         0          0             0           0            1
18         1          0             0           0            0
19         1          0             0           0            0
20         0          0             0           0            0
21         0          0             1           0            0
22         1          0             0           0            0
23         0          0             0           0            0
24         1          0             0           0            0
25         0          1             0           0            0
26         1          0             0           0            0
27         0          0             0           0            0
28         1          0             0           0            0
29         0          0             0           0            0
30         0          0             1           0            0
31         1          0             0           0            0

[32 rows x 22 columns]

In [9]:
#Save dataframe as csv files without index
one_hot_encoded_data.to_csv(r'Encoded.csv', index = False)